[diff2d]
# Domain dimensions
LX = 10.0
LY = 10.0
# Diffusion constant
D  = .2
# Resolution
DX = .00625
DY = .00625
# Duration to simulate
TIME = 30.0
# Output interval
OUTPUT = 1.0
# Output file
OUTFILE = snapshot.bin
# Driving force
OMEGA=2
K=3